export default {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "scope-enum": [
      2,
      "always",
      [
        "types",
        "config",
        "errors",
        "logger",
        "crypto",
        "db",
        "auth",
        "queue",
        "vector-store",
        "embeddings",
        "chunker",
        "parser",
        "core",
        "reranker",
        "compressor",
        "evaluator",
        "cache",
        "colpali",
        "memory",
        "connectors",
        "sdk",
        "api",
        "worker",
        "dashboard",
        "mcp-server",
        "infra",
        "ci",
        "docs",
      ],
    ],
    "type-enum": [
      2,
      "always",
      ["feat", "fix", "docs", "style", "refactor", "perf", "test", "build", "ci", "chore"],
    ],
  },
};
